//! Automated end-to-end integration tests for Network Bootstrap (Sub-Epic 6, NTEST1..NTEST6).

use std::fs;
use std::path::PathBuf;
use aiosh_core::network_config::NetworkConfig;
use aiosh_core::network_service::NetworkService;
use tempfile::{tempdir, TempDir};

/// Helper fixture for generating hermetic mock network filesystem environments.
pub struct MockNetworkEnv {
    pub dir: TempDir,
    pub sysfs_path: PathBuf,
    pub procfs_path: PathBuf,
    pub resolv_path: PathBuf,
}

impl MockNetworkEnv {
    pub fn new() -> Self {
        let dir = tempdir().expect("create temp dir");
        let sysfs_path = dir.path().join("sys/class/net");
        let procfs_path = dir.path().join("proc/net");
        let resolv_path = dir.path().join("etc/resolv.conf");

        fs::create_dir_all(&sysfs_path).expect("create mock sysfs");
        fs::create_dir_all(&procfs_path).expect("create mock procfs");
        fs::create_dir_all(resolv_path.parent().unwrap()).expect("create mock etc");

        Self {
            dir,
            sysfs_path,
            procfs_path,
            resolv_path,
        }
    }

    pub fn populate_standard_fixtures(&self) {
        // lo (loopback)
        let lo = self.sysfs_path.join("lo");
        fs::create_dir_all(&lo).unwrap();
        fs::write(lo.join("operstate"), "unknown\n").unwrap();
        fs::write(lo.join("address"), "00:00:00:00:00:00\n").unwrap();
        fs::write(lo.join("mtu"), "65535\n").unwrap();
        fs::write(lo.join("flags"), "0x9\n").unwrap(); // IFF_UP | IFF_LOOPBACK

        // eth0 (ethernet, up)
        let eth0 = self.sysfs_path.join("eth0");
        fs::create_dir_all(&eth0).unwrap();
        fs::write(eth0.join("operstate"), "up\n").unwrap();
        fs::write(eth0.join("address"), "00:11:22:33:44:55\n").unwrap();
        fs::write(eth0.join("mtu"), "1500\n").unwrap();
        fs::write(eth0.join("flags"), "0x1003\n").unwrap(); // IFF_UP | IFF_BROADCAST | IFF_MULTICAST

        // wlan0 (wireless, down)
        let wlan0 = self.sysfs_path.join("wlan0");
        fs::create_dir_all(&wlan0).unwrap();
        fs::write(wlan0.join("operstate"), "down\n").unwrap();
        fs::write(wlan0.join("address"), "aa:bb:cc:dd:ee:ff\n").unwrap();
        fs::write(wlan0.join("mtu"), "1500\n").unwrap();
        fs::write(wlan0.join("flags"), "0x1002\n").unwrap();

        // /proc/net/route
        // Default route on eth0: dest 00000000, gw 0101A8C0 (192.168.1.1), flags 0003 (RTF_UP|RTF_GATEWAY), metric 100
        // Subnet route on eth0: dest 0001A8C0 (192.168.1.0), gw 00000000, flags 0001 (RTF_UP), metric 0
        let route_content = "Iface\tDestination\tGateway\tFlags\tRefCnt\tUse\tMetric\tMask\tMTU\tWindow\tIRTT\n\
                             eth0\t00000000\t0101A8C0\t0003\t0\t0\t100\t00000000\t0\t0\t0\n\
                             eth0\t0001A8C0\t00000000\t0001\t0\t0\t0\t00FFFFFF\t0\t0\t0\n";
        fs::write(self.procfs_path.join("route"), route_content).unwrap();

        // /etc/resolv.conf
        let resolv_content = "# Generated by NetworkManager\n\
                              nameserver 1.1.1.1\n\
                              nameserver 8.8.8.8\n\
                              search localdomain example.com\n";
        fs::write(&self.resolv_path, resolv_content).unwrap();
    }
}

#[test]
fn test_automated_mock_discovery_happy_path() {
    let mock = MockNetworkEnv::new();
    mock.populate_standard_fixtures();

    let service = NetworkService::with_paths(&mock.sysfs_path, &mock.procfs_path, &mock.resolv_path);

    // Interfaces
    let ifaces = service.scan_interfaces().expect("scan_interfaces");
    assert_eq!(ifaces.len(), 3);
    assert_eq!(ifaces[0].name, "eth0");
    assert_eq!(ifaces[1].name, "lo");
    assert_eq!(ifaces[2].name, "wlan0");

    // Routes
    let routes = service.scan_routes().expect("scan_routes");
    assert_eq!(routes.len(), 2);
    assert_eq!(routes[0].destination, "192.168.1.0/24");
    assert_eq!(routes[1].destination, "0.0.0.0/0");

    // DNS
    let dns = service.get_dns_config().expect("get_dns_config");
    assert_eq!(dns.nameservers, vec!["1.1.1.1", "8.8.8.8"]);
    assert_eq!(dns.search_domains, vec!["localdomain", "example.com"]);

    // Full Unified State
    let state = service.get_network_state().expect("get_network_state");
    assert_eq!(state.interfaces.len(), 3);
    assert_eq!(state.routes.len(), 2);
    assert_eq!(state.dns.nameservers.len(), 2);
}

#[test]
fn test_automated_config_integration() {
    let mock = MockNetworkEnv::new();
    mock.populate_standard_fixtures();

    let mut cfg = NetworkConfig::default();
    cfg.sysfs_net_path = mock.sysfs_path.clone();
    cfg.procfs_path = mock.procfs_path.clone();
    cfg.resolv_conf_path = mock.resolv_path.clone();
    assert!(cfg.validate().is_ok());

    let save_file = mock.dir.path().join("saved_network_config.json");
    cfg.save_to_path(&save_file).expect("save_to_path");

    let loaded = NetworkConfig::load_from_path(&save_file).expect("load_from_path");
    assert_eq!(cfg, loaded);
}

#[test]
fn test_automated_fault_injection_missing_sysfs() {
    let mock = MockNetworkEnv::new();
    let missing_sysfs = mock.dir.path().join("non_existent_sysfs");

    let service = NetworkService::with_paths(&missing_sysfs, &mock.procfs_path, &mock.resolv_path);
    let ifaces = service.scan_interfaces().expect("scan_interfaces on missing sysfs");
    assert!(ifaces.is_empty());
}

#[test]
fn test_automated_fault_injection_corrupt_routes() {
    let mock = MockNetworkEnv::new();
    mock.populate_standard_fixtures();

    // Overwrite route with corrupt data
    let corrupt_content = "Iface\tDestination\tGateway\tFlags\tRefCnt\tUse\tMetric\tMask\tMTU\tWindow\tIRTT\n\
                           corrupt_row_without_enough_columns\n\
                           eth0\tNOT_HEX\tNOT_HEX\t0001\t0\t0\t0\t00FFFFFF\t0\t0\t0\n";
    fs::write(mock.procfs_path.join("route"), corrupt_content).unwrap();

    let service = NetworkService::with_paths(&mock.sysfs_path, &mock.procfs_path, &mock.resolv_path);
    let routes = service.scan_routes().expect("scan_routes handles corrupt rows");
    // Invalid rows should be skipped without panic
    assert!(routes.is_empty());
}

#[test]
fn test_automated_fault_injection_empty_resolv() {
    let mock = MockNetworkEnv::new();
    mock.populate_standard_fixtures();

    // Overwrite resolv.conf with empty file
    fs::write(&mock.resolv_path, "").unwrap();

    let service = NetworkService::with_paths(&mock.sysfs_path, &mock.procfs_path, &mock.resolv_path);
    let dns = service.get_dns_config().expect("get_dns_config handles empty file");
    assert!(dns.nameservers.is_empty());
    assert!(dns.search_domains.is_empty());
}

#[test]
fn test_automated_link_state_transitions() {
    let mock = MockNetworkEnv::new();
    mock.populate_standard_fixtures();

    let service = NetworkService::with_paths(&mock.sysfs_path, &mock.procfs_path, &mock.resolv_path);

    // Bring up wlan0
    assert!(service.bring_up("wlan0").is_ok());

    // Bring down eth0
    assert!(service.bring_down("eth0").is_ok());
}
